apiVersion: apps/v1
kind: Deployment
metadata:
    name: cloudsqlproxy
spec:
    replicas: 1
    selector:
      matchLabels:
        app: cloudsqlproxy
    template:
      metadata:
          labels:
              app: cloudsqlproxy
      spec:
          containers:
          # Make sure to specify image tag in production
          # Check out the newest version in release page
          # https://github.com/GoogleCloudPlatform/cloudsql-proxy/releases
          - name: cloud-sql-proxy
            image: gcr.io/cloudsql-docker/gce-proxy:1.17
            command:
            - /cloud_sql_proxy
            - -dir=/cloudsql
            - -instances=poccomposer:calendar=tcp:0.0.0.0:3306
            - -credential_file=credentials.json
            - term_timeout=10s
          securityContext:
            runAsNonRoot: true
         
        